### ISSUE TITLE
Error when trying to run Flutter 2

### ISSUE THREAD

**Issue by doble-d** [znjameswu/flutter_math#38] opened 2021-03-04 17:35 UTC
Just upgraded my Flutter SDK to the new version  (Flutter 2) and I get and error when trying to run the project or build an apk:

```
flutter_math: ^0.2.1
```

```
~$ flutter --version
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git   
Framework • revision 60bd88df91 (24 hours ago) • 2021-03-03 09:12:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

```
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_math-0.2.1/lib/src/widgets/selection/overlay.dart:302:46: Error: Too few positional arguments: 8 required, 7 given.
        child: selectionControls.buildToolbar
```

**Comment by walsha2** [comment] 2021-03-05 03:03
Having the same exact issue - this is a duplicate of #37. Please close this issue and move discussion there.

**Comment by walsha2** [comment] 2021-03-05 04:05
Please see #39 pull request to resolve #37 - and in turn this issue. Awaiting approval from @znjameswu

**Closed as completed** 2021-03-08 04:53 UTC
